# Generated by Django 2.2.3 on 2019-07-28 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0002_itinerary_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itinerary',
            old_name='isPublished',
            new_name='is_published',
        ),
    ]
