# Generated by Django 2.2.3 on 2019-08-03 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0003_auto_20190728_1905'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itinerary',
            options={'verbose_name_plural': 'Itineraries'},
        ),
    ]
