# Generated by Django 2.2.3 on 2019-08-03 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0004_auto_20190803_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='POI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('location_type', models.CharField(choices=[('OTHER', 'Other'), ('RESTAURANT', 'Restaurant'), ('HISTORICAL', 'Historical Site'), ('RELIGOUS', 'Religous'), ('THEME PARK', 'Theme Park'), ('TOURIST ATTACTION', 'Tourist Attaction'), ('BAR', 'Bar'), ('STADIUM', 'Stadium'), ('BEACH', 'Beach'), ('MUSEUM', 'Museum'), ('PARK', 'Park'), ('HOTEL', 'Hotel'), ('HIKING', 'Hiking Trail')], default='OTHER', max_length=255)),
                ('order', models.IntegerField()),
                ('address', models.CharField(max_length=255, null=True)),
                ('image', models.CharField(max_length=255, null=True)),
                ('website', models.CharField(max_length=2083, null=True)),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itinerary.Itinerary')),
            ],
            options={
                'verbose_name_plural': 'Points of Interest',
                'ordering': ['order'],
            },
        ),
    ]
